#!/usr/bin/env bash

display_usage() {
  echo "Usage: permit <spender> <value> <nonce> [deadline]"
}

if [ $# -lt 3 ];  then
    display_usage
    exit 1
fi

if [ -z ${ETH_FROM+x} ]; then
    echo "ETH_FROM must be set";
    exit 1
fi

export NETWORK=${NETWORK:-mainnet}
# shellcheck source=conf.sh
source "${0%/*}/conf.sh"
DOMAIN_SEPARATOR=$("${0%/*}/domain_separator.sh")
#
# permit type data
permit_TYPEHASH=$(seth keccak $(seth --from-ascii "Permit(address owner,address spender,uint256 value,uint256 nonce,uint256 deadline)"))

echo "DOMAIN_SEPARATOR $DOMAIN_SEPARATOR"
# permit data
OWNER=$ETH_FROM
SPENDER=$1
VALUE=$2
NONCE=$3
DEADLINE=1699062789

echo "Sign the following permit?"
echo "OWNER $OWNER"
echo "SPENDER $SPENDER"
echo "VALUE $VALUE"
echo "DEADLINE $DEADLINE"
echo "Enter passphrase for $ETH_FROM"

MESSAGE=0x1901\
$(echo $DOMAIN_SEPARATOR\
$(seth keccak \
$permit_TYPEHASH\
$(echo $(seth --to-uint256 $OWNER)\
$(seth --to-uint256 $SPENDER)\
$(seth --to-uint256 $VALUE)\
$(seth --to-uint256 $NONCE)\
$(seth --to-uint256 $DEADLINE)\
      | sed 's/0x//g')) \
      | sed 's/0x//g')
SIG=$(ethsign msg --key-store . --no-prefix --data $MESSAGE)

printf '{"permit": {"owner":"%s","spender":"%s","value":"%s", "deadline": "%s", "v": "%s", "r": "%s", "s": "%s"}}\n' "$OWNER" "$SPENDER" "$VALUE" "$DEADLINE" $((0x$(echo "$SIG" | cut -c 131-132))) $(echo "$SIG" | cut -c 1-66) "0x"$(echo "$SIG" | cut -c 67-130)
